### ISSUE TITLE
some thing about the environment configuration

### ISSUE THREAD

**Issue by bbruceyuan** [UKPLab/acl2017-neural_end2end_am#2]
hello

I am really interest in your great work in AM. Some problems confused me a long time when I tried my best to reproduce the result of your paper.

- Question one: 
When I run the model BiLSTM-CNN-CRF, I found that the repo _BiLSTM-CNN-CRF: https://github.com/XuezheMax/LasagneNLP_ was not supported any more, so I use that author's new repo [NeuroNLP2](https://github.com/XuezheMax/NeuroNLP2). Then there was problem like [this](https://github.com/XuezheMax/NeuroNLP2/issues/4). maybe it's because label is too much. do you have any idea?
- Question two:
as I found that I can't use the new repo "NeroNLP2", I extract your /BiLSTM-CNN-CRF/acl2017.tgz, it's  not ok for theano's new edition . So can u share your requirements of the project with specific edition of the used package? especially the theano's edition because Theano's api had been changed. 

thank you very much

**Comment by SteffenEger** [comment]
Hi, 

thanks for your interest. 

Concerning problem 1: If they set up something new, I don't unfortunately know what to do in case it doesn't work anymore.

Concerning problem 2: Does it run with theano version 0.9.0? I'm unfortunately not sure anymore which version we used at the time.

Finally, I recommend you try this implementation in the mean time: 
https://github.com/UKPLab/emnlp2017-bilstm-cnn-crf

I think it's both faster and more user-friendly than the other implementations, but implementing the same model.
