### ISSUE TITLE
Undefined argument to run_bi-lstm-cnn-crf3.sh

### ISSUE THREAD

**Issue by roopalv54** [UKPLab/acl2017-neural_end2end_am#3]
In the script runACL_paragraph_sub.sh, the 4th argument MODELS/sub_paragraph${i}.mod is not defined. Can you please explain this

**Comment by SteffenEger** [comment]
Did you take the implementation in ACL2017.tgz?

**Comment by lintingxue** [comment]
I am using the code in ACL2017.tgz, it shows train="data/POS-penn/wsj/split1/wsj1.train.original", I don't think the dataset is in the 'data' folder.

**Comment by lintingxue** [comment]
It seems like runACL_paragraph_sub.sh in the ACL2017.tgz takes different dataset but not the data in data/conll.  Can you update it to make it runnable on the data in this repository (data/conll/train.dat dev.dat test.dat)?

**Comment by SteffenEger** [comment]
You need to specify the data as argument to the *sh script.

**Comment by lintingxue** [comment]
Thanks! It is working now.
